<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>uk.gov.defra.tracesx</groupId>
  <artifactId>spring-boot-parent</artifactId>
  <version>4.0.54</version>
  <packaging>pom</packaging>

  <name>TracesX-Spring-Boot-Parent</name>
  <url>http://maven.apache.org</url>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.3.1</version>
  </parent>

  <distributionManagement>
    <snapshotRepository>
      <id>release</id>
      <name>Snapshots</name>
      <url>https://artifactoryv2.azure.defra.cloud/artifactory/maven-snapshots-local</url>
    </snapshotRepository>
    <repository>
      <id>release</id>
      <name>Releases</name>
      <url>${repo.releases.url}</url>
    </repository>
  </distributionManagement>

  <scm>
    <connection>scm:git:https://github.com/DEFRA/ipaffs-spring-boot-parent.git</connection>
    <tag>4.0.54-759</tag>
  </scm>

  <properties>
    <project.scm.id>github</project.scm.id>

    <java.version>21</java.version>

    <tracesx.common.version>4.0.3</tracesx.common.version>
    <tracesx.common.security.version>4.0.6</tracesx.common.security.version>
    <tracesx.notification.schema.version>4.0.59</tracesx.notification.schema.version>
    <applicationinsights-core.version>3.4.19</applicationinsights-core.version>
    <azure.springboot.metricsstarter.version>2.3.5</azure.springboot.metricsstarter.version>
    <azure.version>2.3.3</azure.version>
    <azureidentity.version>1.11.2</azureidentity.version>
    <checkstyle.version>10.12.2</checkstyle.version>
    <commons.beanutils.version>1.9.4</commons.beanutils.version>
    <equalsverifier.version>3.15.1</equalsverifier.version>
    <git-build-hook-maven-plugin.version>3.4.1</git-build-hook-maven-plugin.version>
    <guava.version>32.1.2-jre</guava.version>
    <hibernate.version>6.4.1.Final</hibernate.version>
    <io.micrometer.micrometer-core.version>1.11.3</io.micrometer.micrometer-core.version>
    <jacoco.maven.plugin.version>0.8.10</jacoco.maven.plugin.version>
    <jjwt.version>0.11.5</jjwt.version>
    <json.version>20240303</json.version>
    <json.patch.version>1.9</json.patch.version>
    <maven.checkstyle.version>3.3.0</maven.checkstyle.version>
    <maven-dependency-analyzer.version>1.13.2</maven-dependency-analyzer.version>
    <maven-dependency-plugin.version>3.6.0</maven-dependency-plugin.version>
    <maven.deploy.plugin.version>3.1.1</maven.deploy.plugin.version>
    <maven.help.plugin.version>3.4.0</maven.help.plugin.version>
    <maven.jar.plugin.version>3.3.0</maven.jar.plugin.version>
    <maven-release-plugin.version>3.0.1</maven-release-plugin.version>
    <maven-remote-resources-plugin.version>3.1.0</maven-remote-resources-plugin.version>
    <maven.versions.plugin.version>2.16.0</maven.versions.plugin.version>
    <mssql.jdbc.version>11.2.0.jre17</mssql.jdbc.version>
    <neovisionaries.version>1.29</neovisionaries.version>
    <everit-json-schema.version>1.14.4</everit-json-schema.version>
    <org.owasp.encoder.version>1.2.3</org.owasp.encoder.version>
    <shared-resources.version>1.0.1</shared-resources.version>
    <snakeyaml.version>2.1</snakeyaml.version>
    <woodstox-core.version>6.5.1</woodstox-core.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>uk.gov.defra.tracesx</groupId>
        <artifactId>TracesX-SpringBoot-Common-Azure</artifactId>
        <version>${tracesx.common.version}</version>
      </dependency>
      <dependency>
        <groupId>uk.gov.defra.tracesx</groupId>
        <artifactId>TracesX-SpringBoot-Common-Health</artifactId>
        <version>${tracesx.common.version}</version>
      </dependency>
      <dependency>
        <groupId>uk.gov.defra.tracesx</groupId>
        <artifactId>TracesX-SpringBoot-Common-Event</artifactId>
        <version>${tracesx.common.version}</version>
      </dependency>
      <dependency>
        <groupId>uk.gov.defra.tracesx</groupId>
        <artifactId>TracesX-SpringBoot-Common-Logging</artifactId>
        <version>${tracesx.common.version}</version>
      </dependency>
      <dependency>
        <groupId>uk.gov.defra.tracesx</groupId>
        <artifactId>TracesX-SpringBoot-CommonSecurity-Config</artifactId>
        <version>${tracesx.common.security.version}</version>
      </dependency>
      <dependency>
        <groupId>uk.gov.defra.tracesx</groupId>
        <artifactId>notification-schema-core</artifactId>
        <version>${tracesx.notification.schema.version}</version>
      </dependency>
      <dependency>
        <groupId>uk.gov.defra.tracesx</groupId>
        <artifactId>notification-schema-java</artifactId>
        <version>${tracesx.notification.schema.version}</version>
      </dependency>
      <dependency>
        <groupId>commons-beanutils</groupId>
        <artifactId>commons-beanutils</artifactId>
        <version>${commons.beanutils.version}</version>
      </dependency>
      <dependency>
        <groupId>io.micrometer</groupId>
        <artifactId>micrometer-core</artifactId>
        <version>${io.micrometer.micrometer-core.version}</version>
      </dependency>
      <dependency>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure-spring-boot-bom</artifactId>
        <version>${azure.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>applicationinsights-core</artifactId>
        <version>${applicationinsights-core.version}</version>
      </dependency>
      <dependency>
        <groupId>com.azure</groupId>
        <artifactId>azure-identity</artifactId>
        <version>${azureidentity.version}</version>
      </dependency>
      <dependency>
        <groupId>com.github.fge</groupId>
        <artifactId>json-patch</artifactId>
        <version>${json.patch.version}</version>
      </dependency>
      <dependency>
        <groupId>com.github.erosb</groupId>
        <artifactId>everit-json-schema</artifactId>
        <version>${everit-json-schema.version}</version>
      </dependency>
      <dependency>
        <groupId>com.microsoft.sqlserver</groupId>
        <artifactId>mssql-jdbc</artifactId>
        <version>${mssql.jdbc.version}</version>
      </dependency>
      <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>${guava.version}</version>
      </dependency>
      <dependency>
        <groupId>nl.jqno.equalsverifier</groupId>
        <artifactId>equalsverifier</artifactId>
        <version>${equalsverifier.version}</version>
      </dependency>
      <dependency>
        <groupId>com.h2database</groupId>
        <artifactId>h2</artifactId>
        <version>${h2.version}</version>
      </dependency>
      <dependency>
        <groupId>org.hibernate.orm</groupId>
        <artifactId>hibernate-core</artifactId>
        <version>${hibernate.version}</version>
      </dependency>
      <dependency>
        <groupId>org.json</groupId>
        <artifactId>json</artifactId>
        <version>${json.version}</version>
      </dependency>
      <dependency>
        <groupId>com.fasterxml.woodstox</groupId>
        <artifactId>woodstox-core</artifactId>
        <version>${woodstox-core.version}</version>
      </dependency>
      <dependency>
        <groupId>com.neovisionaries</groupId>
        <artifactId>nv-i18n</artifactId>
        <version>${neovisionaries.version}</version>
      </dependency>
      <dependency>
        <groupId>org.owasp.encoder</groupId>
        <artifactId>encoder</artifactId>
        <version>${org.owasp.encoder.version}</version>
      </dependency>
      <dependency>
        <groupId>io.jsonwebtoken</groupId>
        <artifactId>jjwt-api</artifactId>
        <version>${jjwt.version}</version>
      </dependency>
      <dependency>
        <groupId>io.jsonwebtoken</groupId>
        <artifactId>jjwt-impl</artifactId>
        <version>${jjwt.version}</version>
      </dependency>
      <dependency>
        <groupId>io.jsonwebtoken</groupId>
        <artifactId>jjwt-jackson</artifactId>
        <version>${jjwt.version}</version>
      </dependency>
      <dependency>
        <groupId>org.yaml</groupId>
        <artifactId>snakeyaml</artifactId>
        <version>${snakeyaml.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>uk.gov.defra.tracesx</groupId>
      <artifactId>TracesX-SpringBoot-CommonSecurity-Config</artifactId>
    </dependency>
    <dependency>
      <groupId>uk.gov.defra.tracesx</groupId>
      <artifactId>TracesX-SpringBoot-Common-Logging</artifactId>
    </dependency>
    <dependency>
      <groupId>uk.gov.defra.tracesx</groupId>
      <artifactId>TracesX-SpringBoot-Common-Health</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web-services</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents.client5</groupId>
      <artifactId>httpclient5</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpasyncclient</artifactId>
    </dependency>
    <dependency>
      <groupId>com.github.fge</groupId>
      <artifactId>json-patch</artifactId>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <type>jar</type>
    </dependency>
    <!-- TODO: IMTS-4606 It would be nice to have a separate persistence parent -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
    </dependency>
    <!-- END TODO -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>com.vaadin.external.google</groupId>
          <artifactId>android-json</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-params</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.vintage</groupId>
      <artifactId>junit-vintage-engine</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-inline</artifactId>
      <version>5.2.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>nl.jqno.equalsverifier</groupId>
      <artifactId>equalsverifier</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.hibernate.orm</groupId>
      <artifactId>hibernate-core</artifactId>
    </dependency>
    <dependency>
      <groupId>jakarta.persistence</groupId>
      <artifactId>jakarta.persistence-api</artifactId>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-dependency-plugin</artifactId>
          <version>${maven-dependency-plugin.version}</version>
          <dependencies>
            <dependency>
              <groupId>org.apache.maven.shared</groupId>
              <artifactId>maven-dependency-analyzer</artifactId>
              <version>${maven-dependency-analyzer.version}</version>
            </dependency>
          </dependencies>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>${maven.deploy.plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-help-plugin</artifactId>
          <version>${maven.help.plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <version>${maven.jar.plugin.version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-release-plugin</artifactId>
          <version>${maven-release-plugin.version}</version>
          <configuration>
            <autoVersionSubmodules>true</autoVersionSubmodules>
            <tagNameFormat>@{project.version}-${env.BUILD_NUMBER}</tagNameFormat>
            <releaseProfiles>release</releaseProfiles>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>versions-maven-plugin</artifactId>
          <version>${maven.versions.plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-maven-plugin</artifactId>
          <executions>
            <execution>
              <goals>
                <goal>repackage</goal>
              </goals>
            </execution>
            <execution>
              <id>default-cli</id>
              <configuration>
                <jvmArguments>-Dspring.config.additional-location=file:./</jvmArguments>
                <profiles>
                  <profile>default</profile>
                  <profile>local</profile>
                </profiles>
              </configuration>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.jacoco</groupId>
          <artifactId>jacoco-maven-plugin</artifactId>
          <version>${jacoco.maven.plugin.version}</version>
          <configuration>
            <excludes>
              <exclude>**/traceswsns/**/*</exclude>
            </excludes>
          </configuration>
          <executions>
            <execution>
              <id>default-prepare-agent</id>
              <goals>
                <goal>prepare-agent</goal>
              </goals>
            </execution>
            <execution>
              <id>default-check</id>
              <goals>
                <goal>check</goal>
              </goals>
              <configuration>
                <rules>
                  <rule implementation="org.jacoco.maven.RuleConfiguration">
                    <element>BUNDLE</element>
                    <limits>
                      <limit implementation="org.jacoco.report.check.Limit">
                        <counter>LINE</counter>
                        <value>COVEREDRATIO</value>
                      </limit>
                    </limits>
                  </rule>
                </rules>
              </configuration>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <configuration>
            <useDefaultDelimiters>true</useDefaultDelimiters>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-checkstyle-plugin</artifactId>
          <version>${maven.checkstyle.version}</version>
          <dependencies>
            <dependency>
              <groupId>com.puppycrawl.tools</groupId>
              <artifactId>checkstyle</artifactId>
              <version>${checkstyle.version}</version>
            </dependency>
          </dependencies>
          <configuration>
            <configLocation>${project.build.directory}/maven-shared-archive-resources/google_checks_ipaffs.xml</configLocation>
            <suppressionsLocation>${project.build.directory}/maven-shared-archive-resources/checkstyle-suppressions.xml</suppressionsLocation>
            <logViolationsToConsole>true</logViolationsToConsole>
            <outputFile>${project.build.directory}/checkstyle-result.xml</outputFile>
            <violationSeverity>warning</violationSeverity>
            <failsOnError>true</failsOnError>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>check</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>com.rudikershaw.gitbuildhook</groupId>
          <artifactId>git-build-hook-maven-plugin</artifactId>
          <version>${git-build-hook-maven-plugin.version}</version>
          <configuration>
            <gitConfig>
              <core.hooksPath>hooks</core.hooksPath>
            </gitConfig>
          </configuration>
          <executions>
            <execution>
              <id>configure-git-hooks</id>
              <goals>
                <goal>configure</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-remote-resources-plugin</artifactId>
          <version>${maven-remote-resources-plugin.version}</version>
          <configuration>
            <resourceBundles>
              <resourceBundle>uk.gov.defra.tracesx:shared-resources:${shared-resources.version}</resourceBundle>
            </resourceBundles>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>process</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>com.rudikershaw.gitbuildhook</groupId>
        <artifactId>git-build-hook-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-remote-resources-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>jenkins</id>
      <build>
        <plugins>
          <plugin>
            <groupId>com.rudikershaw.gitbuildhook</groupId>
            <artifactId>git-build-hook-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>configure-git-hooks</id>
                <phase>none</phase>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
